# Generated by Django 2.1 on 2018-08-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coda', '0002_paziente_rif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paziente',
            options={'permissions': (('can_see_all', 'Can see all pazienti'),)},
        ),
    ]
