# Generated by Django 2.1 on 2018-09-04 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coda', '0007_auto_20180904_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paziente',
            name='id',
        ),
        migrations.AlterField(
            model_name='paziente',
            name='rif',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
