# Generated by Django 2.1 on 2018-09-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coda', '0009_priority_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='color',
            field=models.CharField(max_length=15),
        ),
    ]
