# Generated by Django 2.1 on 2018-09-25 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coda', '0010_auto_20180925_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paziente',
            name='priority_val',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
    ]
