# Generated by Django 2.1 on 2018-10-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coda', '0012_priority_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
