# Generated by Django 2.1 on 2018-10-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coda', '0013_auto_20181001_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
