# Generated by Django 2.1 on 2018-09-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coda', '0008_auto_20180904_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='color',
            field=models.TextField(default='white'),
            preserve_default=False,
        ),
    ]
