# Generated by Django 2.1 on 2018-10-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coda', '0011_auto_20180925_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
